<a href="https://colab.research.google.com/github/yaswanth-kumar546/NUMPY_LEARNING/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

HERE I AM LEARNING NUMPY

NumPy is a powerful Python library that can manage different types of data. Here we will explore the Datatypes in NumPy and How we can check and create datatypes of the NumPy array.

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
import numpy as np

Numpy is a powerful library in Python that is used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. Here are some basic concepts of Numpy:
1. Arrays: Numpy provides a powerful array object called ndarray, which is a multi-dimensional array that can hold elements of the same data type. It allows for efficient storage and manipulation of large datasets.

2. Vectorized Operations: Numpy allows for vectorized operations, which means that you can perform operations on entire arrays without the need for explicit loops. This leads to faster and more efficient code.

3. Broadcasting: Numpy supports broadcasting, which is a powerful mechanism that allows operations to be performed on arrays of different shapes and sizes. It automatically adjusts the shapes of the arrays to make them compatible for operations.

4. Universal Functions (ufuncs): Numpy provides a set of universal functions that operate element-wise on arrays. These functions are optimized for performance and can be applied to arrays of any shape.

5. Indexing and Slicing: Numpy allows for advanced indexing and slicing techniques to access and manipulate specific elements or subsets of an array. This includes boolean indexing, fancy indexing, and slicing with steps.

6. Linear Algebra: Numpy provides a comprehensive set of functions for linear algebra operations, including matrix multiplication, eigenvalues, singular value decomposition, and more.

7. Random Number Generation: Numpy includes a module for generating random numbers, which can be used for various applications such as simulations, data analysis, and machine learning.

8. Integration with Other Libraries: Numpy is often used in conjunction with other libraries such as Pandas, Matplotlib, and SciPy for data analysis, visualization, and scientific computing.

Overall, Numpy is a fundamental library for numerical computing in Python and is widely used in various fields such as data science, machine learning, and scientific research.

In [ ]:
import numpy as np
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1[0])
print(arr1)

1D Array:
1
[1 2 3 4 5]


In [ ]:
# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2)
print('shape of the array:', arr2.shape)


2D Array:
[[1 2 3]
 [4 5 6]]
shape of the array: (2, 3)


In [ ]:
# Create a 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(arr3)


3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Perform element-wise addition
arr4 = arr1 + 10
print("\nElement-wise Addition:")
print(arr4)


Element-wise Addition:
[11 12 13 14 15]


In [ ]:
# Perform element-wise multiplication
arr5 = arr1 * 2
print("\nElement-wise Multiplication:")
print(arr5)


Element-wise Multiplication:
[ 2  4  6  8 10]


In [ ]:
# Perform matrix multiplication
arr6 = np.dot(arr2, arr2.T)
print("\nMatrix Multiplication:")
print(arr6)


Matrix Multiplication:
[[14 32]
 [32 77]]


In [ ]:
# Perform broadcasting
arr2_compatible = np.array([[10, 20, 30, 40, 50], [100, 200, 300, 400, 500]])
arr7 = arr1 + arr2_compatible
print("\nBroadcasting:")
print(arr7)


Broadcasting:
[[ 11  22  33  44  55]
 [101 202 303 404 505]]


In [ ]:
# Generate random numbers
random_arr = np.random.rand(3, 3)
print("\nRandom Array:")
print(random_arr)


Random Array:
[[0.61889376 0.6309941  0.0633188 ]
 [0.36465069 0.82699376 0.80224389]
 [0.64112452 0.67270248 0.8880801 ]]


In [ ]:

import sys
#here we are creating list of 1000 integers
list_1000= np.arange(1000)
# print(list_1000)

#here we are creating numpy array of 1000 integers
array_1000 = np.arange(1000)
# print(array_1000)

# here again lets print size of the list and array in bytes
print(f"Size of list: {sys.getsizeof(list_1000)} bytes")
print(f"Size of array: {array_1000.nbytes}, bytes")

# lets take time to check here how long it takes to add list and array

import time

#sum the list
start_time = time.time()
sum_list=sum(list_1000)
end_time=time.time()
list_sum_time= (end_time-start_time) * 1000


# Sum the array
start_time=time.time()
sum_array=np.sum(array_1000)
end_time= time.time()
array_sum_time= (end_time-start_time) * 1000

# Now print the time it take to sum the list and array
print(f"Time to sum list: {list_sum_time:.2f} milliseconds")
print(f"Time to sum array: {array_sum_time: .2f} milliseconds")


Size of list: 8112 bytes
Size of array: 8000, bytes
Time to sum list: 0.30 milliseconds
Time to sum array:  0.21 milliseconds


In [ ]:
# creating an array 0 to 9
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


**Main NumPy Data Types**

1. Numeric Types
Data Type	Description	Example
int8, int16, int32, int64	Signed integers (8, 16, 32, 64 bits)	np.array([1, 2], dtype=np.int16)
uint8, uint16, uint32, uint64	Unsigned integers	np.array([1, 2], dtype=np.uint8)
float16, float32, float64 (or float)	Floating-point numbers	np.array([1.5, 2.5], dtype=np.float32)
complex64, complex128	Complex numbers	np.array([1+2j], dtype=np.complex128)
2. Boolean Type
Data Type	Description	Example
bool_	Boolean values (True/False)	np.array([True, False], dtype=bool)
3. String & Unicode Types
Data Type	Description	Example
string_ (or S)	Fixed-length ASCII strings	np.array(['abc'], dtype='S')
unicode_ (or U)	Fixed-length Unicode strings	np.array(['hello'], dtype='U')
4. Object Type
Data Type	Description	Example
object_	Arbitrary Python objects	np.array([{'a':1}], dtype=object)
5. Datetime & Timedelta Types
Data Type	Description	Example
datetime64	Date & time values	np.array(['2024-01-01'], dtype='datetime64')
timedelta64	Differences between dates/times

In [ ]:
import numpy as np

# Create array with specific dtype
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype)  # int32

# Convert dtype
arr_float = arr.astype(np.float64)
print(arr_float.dtype)  # float64


int32
float64


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4], dtype=np.float64)

# Creating a 3x3 int32 array of zeros
arr2 = np.zeros((3, 3), dtype=np.int32)

# Creating a 2x2 complex128 array of ones
arr3 = np.ones((2, 2), dtype=np.complex128)

# Creating a 1D bool array
arr4 = np.empty((4,), dtype=np.bool_)

# Print the arrays and their data types
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)

Numeric types: integers (int8, int16, int32, int64), unsigned integers (uint8, uint16, etc.), floating-point (float16, float32, float64), and complex numbers (complex64, complex128).

Boolean: bool_ for True/False values.

String and bytes: fixed-width Unicode (str_ / U) and byte strings (bytes_ / S).

Datetime and timedelta: datetime64, timedelta64.

Arbitrary binary data: void type for raw memory blocks.

Python objects: object dtype for heterogeneous data.

In [ ]:
# Here i am going to print the 4d array
arr_4d=np.ones((1,2,3,4))
print(arr_4d)

# Print the number of dimensions
print("number of dimensions:", arr_4d.ndim)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]
number of dimensions: 4


In [ ]:
#Create a 2*3 array filled with zeros
zeros_array=np.zeros((2,3))
print(zeros_array)
print("shape of the array: ",zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]
shape of the array:  [[0. 0. 0.]
 [0. 0. 0.]]


In [1]:
import numpy as np

# Create arrays
arr = np.array([1, 2, 3, 4, 5])
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
randoms = np.random.rand(3, 3)

print(arr)
print(zeros)
print(ones)
print(randoms)

[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.72651391 0.98754531 0.54461517]
 [0.16834521 0.34078881 0.16867153]
 [0.4994937  0.31988424 0.1085685 ]]


In [2]:
x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])

# Element-wise operations
print(x + y)   # [11 22 33 44]
print(x - y)   # [ 9 18 27 36]
print(x * y)   # [10 40 90 160]
print(x / y)   # [10. 10. 10. 10.]

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
C = np.dot(A, B)

# Transpose
T = A.T

# Determinant
det_A = np.linalg.det(A)

# Inverse
inv_A = np.linalg.inv(A)

In [ ]:
arr = np.random.rand(5)   # Random numbers between 0 and 1
print(np.mean(arr))       # Average
print(np.std(arr))        # Standard deviation
print(np.sum(arr))        # Sum
print(np.max(arr))        # Maximum
print(np.min(arr))        # Minimum